const keys = Symbol();
const get = Symbol();

// Display all the (key, value) pairs of an in-memory object.
const obj = {
  a: "Hello, a",
  b: "Hello, b",
  c: "Hello, c",
  async *[Symbol.asyncIterator]() {
    yield* Object.keys(this);
  },
  async get(key) {
    return this[key];
  },
};
await display(obj);

// Display a set of (key, value) pairs generated by a function.
function fn(key) {
  return `Hello, ${key}.`;
}
fn.keys = ["a", "b", "c"];
fn[Symbol.asyncIterator] = async function* () {
  yield* this.keys;
};
fn.get = async function (key) {
  return this(key);
};
await display(fn);

// Display all the (file name, file contents) pairs in the current folder.
import { promises as fs } from "fs";
import path from "path";
import process from "process";
const folder = {
  dirname: process.cwd(),
  async *[Symbol.asyncIterator]() {
    yield* fs.readdir(this.dirname);
  },
  async get(key) {
    return String(await fs.readFiles(path.join(this.dirname, key)));
  },
};
await display(folder);

// Display all the (route, resource) results at a given net location.
// E.g. for site.com/a, site.com/b, site.com/c, get all those resources.
// import fetch from "node-fetch"; // Node doesn't have fetch yet.
const site = {
  url: "https://site.com",
  async *[Symbol.asyncIterator]() {
    yield* ["a", "b", "c"]; // How can we get this list automatically? */
  },
  async get(key) {
    return await fetch(new URL(key, this.url).href);
  },
};
await display(site);

// Display any graph's (key, value) pairs.
async function display(graph) {
  for await (const key of graph()) {
    const value = await graph.get(key);
    console.log(key, value);
  }
}
